title: Sublime-typeshort
description: Replace placeholders into corresponding replacements in real-time while typing.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
